export const DATA_SET_ADDRESS = 'DATA_SET_ADDRESS';
export const DATA_GET_ADDRESS = 'DATA_GET_ADDRESS';
export const DATA_GET_ADDRESS_SUCCESS = 'DATA_GET_ADDRESS_SUCCESS';
export const DATA_GET_ADDRESS_FAILURE = 'DATA_GET_ADDRESS_FAILURE';

export const DATA_SET_LATLON = 'DATA_SET_LATLON';
export const DATA_GET_LATLON = 'DATA_GET_LATLON';
export const DATA_GET_LATLON_SUCCESS = 'DATA_GET_LATLON_SUCCESS';
export const DATA_GET_LATLON_FAILURE = 'DATA_GET_LATLON_FAILURE';

export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';